package plugins.warnings.assertions;

import org.jenkinsci.test.acceptance.plugins.warnings_ng.DefaultWarningsTableRow;

/**
 * Abstract base class for {@link DefaultWarningsTableRow} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractDefaultWarningsTableRowAssert<S extends AbstractDefaultWarningsTableRowAssert<S, A>, A extends DefaultWarningsTableRow>
        extends
        AbstractAbstractNonDetailsIssuesTableRowAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractDefaultWarningsTableRowAssert}</code> to make assertions on actual
     * DefaultWarningsTableRow.
     *
     * @param actual
     *         the DefaultWarningsTableRow we want to make assertions on.
     */
    protected AbstractDefaultWarningsTableRowAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
