package org.jenkinsci.test.acceptance.plugins.warnings.assertions;

import org.jenkinsci.test.acceptance.plugins.warnings.issues_table.DRYIssuesTableRow;

/**
 * {@link DRYIssuesTableRow} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, extend {@link
 * AbstractDRYIssuesTableRowAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class DRYNonDetailsIssuesTableRowAssert
        extends
        AbstractDRYIssuesTableRowAssert<DRYNonDetailsIssuesTableRowAssert, DRYIssuesTableRow> {

    /**
     * Creates a new <code>{@link DRYNonDetailsIssuesTableRowAssert}</code> to make assertions on actual
     * DRYIssuesTableRow.
     *
     * @param actual
     *         the DRYIssuesTableRow we want to make assertions on.
     */
    public DRYNonDetailsIssuesTableRowAssert(DRYIssuesTableRow actual) {
        super(actual, DRYNonDetailsIssuesTableRowAssert.class);
    }

    /**
     * An entry point for DRYNonDetailsIssuesTableRowAssert to follow AssertJ standard <code>assertThat()</code>
     * statements.<br> With a static import, one can write directly: <code>assertThat(myDuplicateWarningsAbstractIssuesTableRow)</code>
     * and get specific assertion with code completion.
     *
     * @param actual
     *         the DRYIssuesTableRow we want to make assertions on.
     *
     * @return a new <code>{@link DRYNonDetailsIssuesTableRowAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static DRYNonDetailsIssuesTableRowAssert assertThat(DRYIssuesTableRow actual) {
        return new DRYNonDetailsIssuesTableRowAssert(actual);
    }
}
