package plugins.warnings.assertions;

import org.jenkinsci.test.acceptance.plugins.warnings.white_mountains.DryIssuesTableRow;

/**
 * {@link DryIssuesTableRow} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, extend {@link
 * AbstractDryIssuesTableRowAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class DryNonDetailsIssuesTableRowAssert
        extends
        AbstractDryIssuesTableRowAssert<DryNonDetailsIssuesTableRowAssert, DryIssuesTableRow> {

    /**
     * Creates a new <code>{@link DryNonDetailsIssuesTableRowAssert}</code> to make assertions on actual
     * DRYIssuesTableRow.
     *
     * @param actual
     *         the DRYIssuesTableRow we want to make assertions on.
     */
    public DryNonDetailsIssuesTableRowAssert(DryIssuesTableRow actual) {
        super(actual, DryNonDetailsIssuesTableRowAssert.class);
    }

    /**
     * An entry point for DRYNonDetailsIssuesTableRowAssert to follow AssertJ standard <code>assertThat()</code>
     * statements.<br> With a static import, one can write directly: <code>assertThat(myDuplicateWarningsAbstractIssuesTableRow)</code>
     * and get specific assertion with code completion.
     *
     * @param actual
     *         the DRYIssuesTableRow we want to make assertions on.
     *
     * @return a new <code>{@link DryNonDetailsIssuesTableRowAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static DryNonDetailsIssuesTableRowAssert assertThat(DryIssuesTableRow actual) {
        return new DryNonDetailsIssuesTableRowAssert(actual);
    }
}
